### ISSUE TITLE
bug使用反馈集合

### ISSUE THREAD

**Issue by JaneYork** [fuzui/form-generator-antdv#1]
1. 空组件下，无法拖动或者不容易拖动（不能拖到中间就生效，而必须拖到顶端），只能点击。
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/29787967/160388052-9c0188a2-1bc3-44a0-a6bc-767e2b8c8000.png">

2. 点击刷新、或开着多个窗口，会重复加载多次，可以点击刷新试试
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/29787967/160387432-bf94b0e8-fc56-40ce-8875-d611f9fb5733.png">

3. 预览JSON - 导出JSON，默认文件名后缀错误
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/29787967/160387652-35309e37-134e-4cb7-8322-1571e8353bb2.png">

4. 多选框组件 ：翻译错误，无法输入错误
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/29787967/160388590-7780237d-7881-48cc-a77a-f8c20a3944c8.png">

**Comment by fuzui** [comment]
已全部修复。
